### PR TITLE
Disable Wayland

### PR DESCRIPTION
**Pull request by pizzadude**
With Wayland on KDE I can't open the input options after exiting a game. With Xwayland it works fine.

### CODE REVIEW

**Comment by SvOlli** [comment]
Stella is using plain SDL2. So I'm trying to pinpoint with who to discuss this problem: flathub or Stella upstream? Any suggestion?

**Comment by hfiguiere** [comment]
there is nothing to discuss. If it desn't work with wayland, disable wayland.

Not that `XWayland` is NOT wayland.

**Comment by sa666666** [comment]
Stella has not been extensively tested with Wayland.  I use KDE, and since SDL doesn't yet have the required server-side decorations, I've not played with it.

I'm not using anything specific in Stella wrt X11, but again, it wouldn't surprise me if something is broken with Wayland.

**Comment by SvOlli** [comment]
Still if there's something that could be fixed, I'd like to let the right people know what to fix.

**Pull request merged**
